### ISSUE TITLE
Add support for Rider?

### ISSUE THREAD

**Issue by EAirPeter** [hmatt1/angelscript-intellij#3]
Hi there,

Is there any plan to add support for Rider?

The motivation is:
1. AngelScript is becoming popular in game development, and there is already an [UnrealEngine-AngelScript](/Hazelight/UnrealEngine-Angelscript) integration. 
2. Rider is the primary JetBrains IDE for game development and it supports UnrealEngine out-of-box, so I believe adding Rider support is a good choice.

Regards,

**Comment by hmatt1** [comment]
Thanks for the request, I will look into it! I recently got an email that a plugin update is needed anyway for compatibility with the 2024.1 version of JetBrains IDEs

**Comment by hmatt1** [comment]
Version [1.4.0r](https://plugins.jetbrains.com/plugin/18276-angelscript-language-support/versions/stable/548941) is now available for Rider
